### ISSUE TITLE
vxAssignNodeCallback test_graph.c sequence issue

### ISSUE THREAD

**Issue by hansely** [KhronosGroup/OpenVX-cts#22]
The graphstate [test](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.3/test_conformance/test_graph.c#L2226) tries to assign a callback to the node to abandon the graph.
The graph flow is as follows:

graph setup -> verifies the graph -> processes the graph -> assign nodecallback

However, in the [openvx specification](https://www.khronos.org/registry/OpenVX/specs/1.3/html/OpenVX_Specification_1_3.html#group_node_callback), figure 11 illustrates the node callback sequence as follows:

graph setup -> assign nodecallback -> verifies the graph -> process the graph

According to the specification, assign nodecallback should happen before verifying & processing the graph.
In the same sense, the verifygraph [test](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.3/test_conformance/test_graph.c#L2416) only removes a node if the graph is not  verified or failed to verify.

**Comment by jessegv** [comment]
[Section 2.14.2](https://www.khronos.org/registry/OpenVX/specs/1.3/html/OpenVX_Specification_1_3.html#sub_lc_graph) in the spec shows that certain changes may require a "reverification" even after verify or execution has happened.

[Section 5.3.3](https://www.khronos.org/registry/OpenVX/specs/1.3/html/OpenVX_Specification_1_3.html#_vxschedulegraph) in the spec describes how if vxScheduleGraph is called and vxVerifyGraph has not been called, then it will be internally called before scheduling the graph to execute.  I can see that this verbage could be clarified to also include if a reverification is necessary due to changes made to the graph since the previous verify call, then it can call verify again.  I will file an issue against the spec to suggest adding this clarity.

I would suggest that the call sequence you are referring to is a general flow, and I agree with you, why would you want to register a node callback after verify if you can just do it before verify.  Having said that, the call sequence does not mean to require that it must be done before the first vxVerifyGraph call.  It can be done after vxVerifyGraph and before another call to vxVerifyGraph.  It just may be that the second call to vxVerifyGraph is hidden within the call to vxScheduleGraph (or vxProcessGraph) if the implementation requires a reverification to happen due to this change to adding a graph callback.  So the test graph sequence can be:

 graph setup -> verifies the graph -> processes the graph -> assign nodecallback ->verifies the graph (hidden inside vxScheduleGraph) -> processes the graph

Please let us know if this puts an undue burden on your  implementation, and we can discuss this in the working group for future spec updates.
